# Generated by Django 3.2.9 on 2022-05-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_orderfields_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderfields',
            options={'ordering': ('modified_at', 'prefix'), 'verbose_name_plural': 'orderfields'},
        ),
        migrations.AddField(
            model_name='orderfields',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
