# Generated by Django 3.2.9 on 2022-06-02 05:56

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20220530_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('quote_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, null=True, region=None, verbose_name='phone')),
                ('quote_email', models.CharField(blank=True, max_length=100, null=True)),
                ('quote_wechat', models.CharField(blank=True, max_length=200, null=True)),
                ('pickup_select', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('internal_order_number', models.CharField(blank=True, max_length=200, null=True)),
                ('pickup_contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, null=True, region=None, verbose_name='phone')),
                ('pickup_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_select', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, null=True, region=None, verbose_name='phone')),
                ('shipping_contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('packaging_board', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('payer', models.CharField(blank=True, max_length=100, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='customer/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'customerfields',
                'db_table': 'customerfields',
                'ordering': ('created_at',),
            },
        ),
    ]
