# Generated by Django 3.2.9 on 2022-06-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_customerfields_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfields',
            name='customer_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
