# Generated by Django 3.2.9 on 2022-06-02 14:55

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_orderfields_customer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfields',
            name='file_size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderfields',
            name='file_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderfields',
            name='customer_link',
            field=models.CharField(default=manager.models.generate_serial, max_length=100, null=True),
        ),
    ]
