# Generated by Django 3.2.9 on 2022-06-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20220602_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfields',
            name='prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
