# Generated by Django 3.2.9 on 2022-06-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_orderlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlogs',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
