# Generated by Django 3.2.9 on 2022-06-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20220605_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlogs',
            name='customer_link',
        ),
    ]
