# Generated by Django 3.2.9 on 2022-06-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_remove_orderlogs_customer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfields',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderfields',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderfields',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderfields',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
