# Generated by Django 3.2.9 on 2022-06-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20220606_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='oders',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='oders',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='oders',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
