# Generated by Django 3.2.9 on 2022-06-21 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20220606_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoIncomingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('cntr', models.CharField(blank=True, max_length=200, null=True)),
                ('mbl', models.CharField(blank=True, max_length=200, null=True)),
                ('seal', models.CharField(blank=True, max_length=200, null=True)),
                ('ship', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.CharField(blank=True, max_length=100, null=True)),
                ('eta', models.CharField(blank=True, max_length=100, null=True)),
                ('drop_city', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.CharField(max_length=100, null=True)),
                ('file_type', models.CharField(max_length=100, null=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'doincomings',
                'db_table': 'doincomings',
                'ordering': ('modified_at',),
            },
        ),
        migrations.AlterField(
            model_name='orderfields',
            name='media',
            field=models.FileField(blank=True, default='', null=True, upload_to='uploads/'),
        ),
    ]
