# Generated by Django 3.2.9 on 2022-06-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20220621_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doincomingsmodel',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'doincomings'},
        ),
        migrations.AddField(
            model_name='orderlogs',
            name='column_33',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderlogs',
            name='demurrage_dolla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderlogs',
            name='empty_in_driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderlogs',
            name='exam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderlogs',
            name='full_out_driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderlogs',
            name='per_diem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderlogs',
            name='pierpass_dolla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderlogs',
            name='ship_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderlogs',
            name='small',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
