# Generated by Django 3.2.9 on 2022-06-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_auto_20220622_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfields',
            name='column_33',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderfields',
            name='demurrage_dolla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderfields',
            name='empty_in_driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderfields',
            name='exam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderfields',
            name='full_out_driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderfields',
            name='per_diem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderfields',
            name='pierpass_dolla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderfields',
            name='ship_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderfields',
            name='small',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
