# Generated by Django 3.2.9 on 2022-06-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_auto_20220622_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfields',
            name='do_recd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderlogs',
            name='do_recd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
