# Generated by Django 3.2.9 on 2022-06-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_auto_20220622_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderfields',
            old_name='small',
            new_name='sml',
        ),
        migrations.RenameField(
            model_name='orderlogs',
            old_name='small',
            new_name='sml',
        ),
    ]
