# Generated by Django 3.2.9 on 2022-06-22 11:48

from django.db import migrations, models
import django.utils.timezone
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20220622_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordername_serial', models.CharField(default=manager.models.generate_serial, max_length=255)),
                ('ordername', models.CharField(max_length=50, null=True, verbose_name='ordername')),
                ('load', models.CharField(default=manager.models.generate_id, max_length=100)),
                ('action', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('pierpass', models.CharField(blank=True, max_length=100, null=True)),
                ('pierpass_dolla', models.CharField(blank=True, max_length=100, null=True)),
                ('exam', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_to', models.CharField(blank=True, max_length=100, null=True)),
                ('full_out_driver', models.CharField(blank=True, max_length=100, null=True)),
                ('empty_in_driver', models.CharField(blank=True, max_length=100, null=True)),
                ('demurrage_dolla', models.CharField(blank=True, max_length=100, null=True)),
                ('per_diem', models.CharField(blank=True, max_length=100, null=True)),
                ('sml', models.CharField(blank=True, max_length=100, null=True)),
                ('column_33', models.CharField(blank=True, max_length=100, null=True)),
                ('do_recd', models.CharField(blank=True, max_length=100, null=True)),
                ('mbl', models.CharField(blank=True, max_length=100, null=True)),
                ('hbl', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('container', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('seal', models.CharField(blank=True, max_length=100, null=True)),
                ('drop_city', models.CharField(blank=True, max_length=100, null=True)),
                ('discharge_port', models.CharField(blank=True, max_length=100, null=True)),
                ('port_eta', models.CharField(blank=True, max_length=100, null=True)),
                ('lfd', models.CharField(blank=True, max_length=100, null=True)),
                ('trucking', models.CharField(blank=True, max_length=100, null=True)),
                ('east_deliver', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_deliver', models.CharField(blank=True, max_length=100, null=True)),
                ('driver', models.CharField(blank=True, max_length=100, null=True)),
                ('empty_return', models.CharField(blank=True, max_length=100, null=True)),
                ('chasis', models.CharField(blank=True, max_length=100, null=True)),
                ('demurrage', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_sent', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_dolla', models.CharField(blank=True, max_length=100, null=True)),
                ('a_rrry', models.CharField(blank=True, max_length=100, null=True)),
                ('a_ppy', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('notify', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('acct_email', models.CharField(max_length=100, null=True)),
                ('customer_link', models.CharField(default=manager.models.generate_serial, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('media', models.FileField(blank=True, default='', null=True, upload_to='uploads/')),
                ('file_size', models.CharField(max_length=100, null=True)),
                ('file_type', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'customer_orders',
                'db_table': 'customer_orders',
                'ordering': ('modified_at', 'prefix'),
            },
        ),
    ]
