# Generated by Django 3.2.9 on 2022-06-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlogs',
            name='ordername',
            field=models.CharField(max_length=50, null=True, verbose_name='ordername'),
        ),
    ]
